// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'employee_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EmployeeModel _$EmployeeModelFromJson(Map<String, dynamic> json) =>
    EmployeeModel(
      empId: (json['empId'] as num).toInt(),
      biometricId: (json['biometricId'] as num).toInt(),
      empFirstName: json['empFirstName'] as String?,
      empLastName: json['empLastName'] as String?,
      dob: json['DOB'] as String?,
      age: (json['age'] as num?)?.toInt(),
      gender: json['Gender'] as String?,
      localAddress: json['LocalAddress'] as String?,
      permanentAddress: json['PermanentAddress'] as String?,
      email: json['email'] as String?,
      contact1: json['Contact1'] as String?,
      contact2: json['Contact2'] as String?,
      bloodgroup: json['bloodgroup'] as String?,
      reference1: json['Reference1'] as String?,
      reference2: json['Reference2'] as String?,
      image: json['image'] as String?,
      maritalStatus: json['MaritalStatus'] as String?,
      bankName: json['BankName'] as String?,
      accountHolderName: json['AccountHolderName'] as String?,
      accountNumber: json['AccountNumber'] as String?,
      branchName: json['BranchName'] as String?,
      status: json['status'] as bool,
      file: json['File'] as String?,
      userName: json['userName'] as String?,
      userPassword: json['userPassword'] as String?,
      remarks: json['remarks'] as String?,
      role: (json['role'] as num).toInt(),
      empcode: json['empcode'] as String?,
      changepass: json['changepass'] as String?,
      employeetype: (json['employeetype'] as num).toInt(),
      department: (json['department'] as num).toInt(),
      levelid: (json['levelid'] as num).toInt(),
      pan: json['pan'] as String?,
      entryDate: json['entryDate'] as String?,
      fromDepName: json['fromDepName'] as String?,
      toDepName: json['toDepName'] as String?,
      dateUpdate: json['dateUpdate'] as String?,
      designation: json['designation'] as String?,
      fromLevelName: json['fromLevelName'] as String?,
      toLevelName: json['toLevelName'] as String?,
      validDate: json['ValidDate'] as String?,
      joinDate: json['joinDate'] as String?,
      reportEmpTypeLst: json['reportEmpTypeLst'] as String?,
      employeeIdd: (json['employeeIdd'] as num).toInt(),
      joinDateChangeSetting: json['joinDateChangeSetting'] as String?,
      validDateChangeSetting: json['validDateChangeSetting'] as String?,
      empValidDateExpired: json['empValidDateExpired'] as String?,
      totalEmployee: (json['totalEmployee'] as num?)?.toInt(),
      totalAbsentEmp: (json['totalAbsentEmp'] as num?)?.toInt(),
      changeDateSetting: json['changeDateSetting'] as String?,
      lmunicipality: json['lmunicipality'] as String?,
      lward: json['lward'] as String?,
      lDistrict: json['lDistrict'] as String?,
      pmunicipality: json['pmunicipality'] as String?,
      pward: json['pward'] as String?,
      pDistrict: json['pDistrict'] as String?,
      flag: json['Flag'] as String?,
    );

Map<String, dynamic> _$EmployeeModelToJson(EmployeeModel instance) =>
    <String, dynamic>{
      'empId': instance.empId,
      'biometricId': instance.biometricId,
      'empFirstName': instance.empFirstName,
      'empLastName': instance.empLastName,
      'DOB': instance.dob,
      'age': instance.age,
      'Gender': instance.gender,
      'LocalAddress': instance.localAddress,
      'PermanentAddress': instance.permanentAddress,
      'email': instance.email,
      'Contact1': instance.contact1,
      'Contact2': instance.contact2,
      'bloodgroup': instance.bloodgroup,
      'Reference1': instance.reference1,
      'Reference2': instance.reference2,
      'image': instance.image,
      'MaritalStatus': instance.maritalStatus,
      'BankName': instance.bankName,
      'AccountHolderName': instance.accountHolderName,
      'AccountNumber': instance.accountNumber,
      'BranchName': instance.branchName,
      'status': instance.status,
      'File': instance.file,
      'userName': instance.userName,
      'userPassword': instance.userPassword,
      'remarks': instance.remarks,
      'role': instance.role,
      'empcode': instance.empcode,
      'changepass': instance.changepass,
      'employeetype': instance.employeetype,
      'department': instance.department,
      'levelid': instance.levelid,
      'pan': instance.pan,
      'entryDate': instance.entryDate,
      'fromDepName': instance.fromDepName,
      'toDepName': instance.toDepName,
      'dateUpdate': instance.dateUpdate,
      'designation': instance.designation,
      'fromLevelName': instance.fromLevelName,
      'toLevelName': instance.toLevelName,
      'ValidDate': instance.validDate,
      'joinDate': instance.joinDate,
      'reportEmpTypeLst': instance.reportEmpTypeLst,
      'employeeIdd': instance.employeeIdd,
      'joinDateChangeSetting': instance.joinDateChangeSetting,
      'validDateChangeSetting': instance.validDateChangeSetting,
      'empValidDateExpired': instance.empValidDateExpired,
      'totalEmployee': instance.totalEmployee,
      'totalAbsentEmp': instance.totalAbsentEmp,
      'changeDateSetting': instance.changeDateSetting,
      'lmunicipality': instance.lmunicipality,
      'lward': instance.lward,
      'lDistrict': instance.lDistrict,
      'pmunicipality': instance.pmunicipality,
      'pward': instance.pward,
      'pDistrict': instance.pDistrict,
      'Flag': instance.flag,
    };
